[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = ["node node_modules/prisma/build/index.js generate"]

[start]
cmd = "node src/index.js"
